Assignment 3 : ECMA Script Features
swatipatil-webonise/JSAssignment pull request #3
Opened 2019-10-01 10:46 UTC by swatipatil-webonise

Problem Statement : 
1) Write a ES code to print numbers by adding delay.
2) Write a ES code to print delay in ES using closure.

2019-10-03 04:59 UTC, deepakb-webonise commented on assignment3/src/problem1_UsingES6.html
> +                    function timeout(iterator) {
No need to create the function here.

2019-10-03 04:59 UTC, deepakb-webonise commented on assignment3/src/problem1_UsingES6.html
> +                    timeout(iterator);
In the case where we define and function and use it, we can go with an anonymous function.

2019-10-03 04:59 UTC, deepakb-webonise commented on assignment3/src/problem1_UsingJS5.html
> +                setInterval(function () {
setInterval should be cleared. The program doesn't stop after printing 10 numbers.

2019-10-03 07:01 UTC, swapnil-webonise requested changes

2019-10-03 07:01 UTC, swapnil-webonise commented on assignment3/src/problem1_UsingJS5.html
> +                setInterval(function () {
Prefer arrow function

2019-10-03 07:01 UTC, swapnil-webonise commented on assignment3/src/problem1_UsingJS5.html
> +                    document.write(counter++ + '<br>');
we can write like

document.write(`${counter + 1} <br>`);

2019-10-04 11:59 UTC, swapnil-webonise approved these changes

2019-10-04 12:00 UTC, swapnil-webonise commented
@deepakb-webonise Merge PR if fine from your end.

2019-10-04 12:03 UTC, deepakb-webonise approved these changes

2019-10-04 12:06 UTC, merged