JSAssignment 4 : Promises in ECMA Script
swatipatil-webonise/JSAssignment pull request #4
Opened 2019-10-03 16:28 UTC by swatipatil-webonise

Problem statement : 
1) Write a ES code to print 1 to 10 using promise.
1) Write a ES
1) Write a ES

2019-10-04 05:08 UTC, deepakb-webonise commented on assignment4/devisionUSingPromise.html
> +        </script>
The Assignment is incorrect. Create a function to add two numbers. the function should return a promise. based on promise resolve or reject, result should be shown.

2019-10-04 05:08 UTC, deepakb-webonise commented on assignment4/print1To10UsingPromise.html
> +            async function printNumbers(endNumber) {
Looks like the assignment is copied from the internet. async and await is introduced in es8 and we haven't covered it.

2019-10-04 05:08 UTC, deepakb-webonise commented on assignment4/print1To10UsingPromise.html
> +            printNumbers(10).then(reject => console.log('rejected'));
if a single function provided then it is called on successfully resolved.

2019-10-04 05:08 UTC, deepakb-webonise commented on assignment4/promiseDemo.html
> +            }
The assignment is incorrect. Create a delay function that will accept the delay seconds and then will return the promise which will resolve in given delay seconds.

2019-10-04 05:08 UTC, deepakb-webonise commented on assignment4/substractionUsingPromise.html
> +            });
The Assignment is incorrect. Create a function to subtract two numbers. the function should return a promise. based on promise resolve or reject, the result should be shown.

2019-10-07 05:26 UTC, deepakb-webonise commented on assignment4/devisionUSingPromise.html
> +                let number1 = parseInt(document.getElementById('number1').value);
This function is tightly coupled with inputs "number1" and "number2". please remove tightly coupling.

2019-10-07 05:26 UTC, deepakb-webonise commented on assignment4/print1To10UsingPromise.html
> +            function getPromise(number) {
give the proper and meaningful function name

2019-10-07 05:26 UTC, deepakb-webonise commented on assignment4/print1To10UsingPromise.html
> +                     if(number <= 10){
no need the check the number. make it generic

2019-10-07 05:26 UTC, deepakb-webonise commented on assignment4/promiseDemo.html
> +                   if (ML > 0) {
no need for this condition

2019-10-07 08:49 UTC, deepakb-webonise approved these changes

2019-10-07 11:10 UTC, swapnil-webonise requested changes

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/devisionUSingPromise.html
> +                then(function (succeed) {
Use flat arrow functions

https://eslint.org/docs/rules/prefer-arrow-callback

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/substractionUsingPromise.html
> +            function getPromiseToDoSubstraction(number1, number2) {
No necessary to use `Promise` word in the function name, simply can be `doSubstraction`

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/substractionUsingPromise.html
> +                let number1 = parseInt(document.getElementById('number1').value);
Prefer `const` over `let`, As we are not modifying value futher

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/substractionUsingPromise.html
> +                let number2 = parseInt(document.getElementById('number2').value);
Same here

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/promiseDemo.html
> +            function delay(ML) {
variable name should be in camelCase and descriptive

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/devisionUSingPromise.html
> +                    if(number2 !== 0) {
Can be written like

`if(number2) {`

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/devisionUSingPromise.html
> +                        resolve(`Devision = ${number1/number2}`);
Check spell

2019-10-07 11:10 UTC, swapnil-webonise commented on assignment4/devisionUSingPromise.html
> +                then(function (succeed) {
Check this across PR

2019-10-07 11:30 UTC, swapnil-webonise approved these changes

2019-10-07 11:30 UTC, merged