JSAssignment5 : React js
swatipatil-webonise/JSAssignment pull request #5
Opened 2019-10-07 08:50 UTC by swatipatil-webonise

Problem Statement : 
1) Create a todo app using react js.

2019-10-10 05:34 UTC, deepakb-webonise commented on todooperation/src/ListTodo.js
> +              <td><button onClick={props.onEdit.bind(null, todo.desc,todo.id)}>Edit</button></td>
No need to pass todo description.

2019-10-10 05:34 UTC, deepakb-webonise commented on todooperation/src/Todo.js
> +            url: "http://localhost:5000/todos"
hardcoded URL are okay for now. but we can create constants for base URL and derive specific endpoints.

2019-10-10 05:34 UTC, deepakb-webonise commented on todooperation/src/Server.js
> +var express = require("express");
no need to add this file, this the dummy backend for this assignment.

2019-10-10 07:14 UTC, swapnil-webonise requested changes

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/AddTodo.js
> +import React from "react";
Use single qutoes

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/AddTodo.js
> +export const AddTodo = (props) => {
props can be destructure here and use them 

```
export const AddTodo = ({
  desc,
  onUserType,
  onAddTodo,
}) => {
```

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/AddTodo.js
> +export const AddTodo = (props) => {
also, prefer full name for props instead of short `desc`

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/App.js
> +import { BrowserRouter as Router, Route, Switch} from "react-router-dom";
Same here

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/App.js
> +class App extends React.Component {
This should functional component

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +            desc: "",
Same here

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +        super(props);
Should be indented with 2 space tab

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +            todos: []
Missing trailing comma

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +            todos: []
Check this across PR

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +            // let t = this.state.todos;
Remove commented code

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/AddTodo.js
> +import React from "react";
Check this across PR

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +        super(props);
Check this across PR

2019-10-10 07:14 UTC, swapnil-webonise commented on todooperation/src/Todo.js
> +        this.state.isUpdate = true;
The state should not be modify directly.

2019-10-10 10:40 UTC, swapnil-webonise approved these changes

2019-10-11 12:02 UTC, deepakb-webonise commented on todooperation/src/Todo.js
> +        }
Use map function over for loop

2019-10-11 12:02 UTC, deepakb-webonise commented on todooperation/src/AddTodo.js
> +      <input type="button" value="add" onClick={onAddTodo}/>
hardcoded label, while updating todo label should be "Update" instead of "Add"

2019-10-14 06:52 UTC, deepakb-webonise approved these changes

2019-10-14 06:52 UTC, deepakb-webonise commented on todooperation/src/Todo.js
> +      isUpdate: false,
no need of buttonValue key as it can be derived from isUpdate key.

2019-10-14 06:52 UTC, merged