JSAssignment 7 : Shopping Cart App With React Redux
swatipatil-webonise/JSAssignment pull request #7
Opened 2019-10-14 07:15 UTC by swatipatil-webonise

Problem Statement : Create a shopping cart using react and redux
Given a list of products give a button to 'add to cart' along with the option to have multiple quantities of the same item(show a ['+' QTY and '-'] button) and a button to 'Checkout'. In the cart calculate the total value of the cart and provide a button to 'Pay Now'(Stub out the 'Pay Now' button). On click of 'Pay Now' button the shopping cart should get cleared.

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/CheckoutProducts.js
> +  checkProductCount() {
use the fat arrow, so that we need not bind this context

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/CheckoutProducts.js
> +    this.state = {
no need state

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/CheckoutProducts.js
> +        <Link to={this.state.url}><input type="button" onClick={this.checkProductCount.bind(this)} value="Check Out"></input></Link><br /><br />
this can be achieved using the conditional rendering. remove the state

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/ShopApp.js
> +  onAdd = (id) => {
can u please give a better name. like "onAddAroduct"

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/store/reducer/todoReducer.js
> +const todoReducer = (state = [], action) => {
give proper name.

2019-10-15 05:36 UTC, deepakb-webonise commented on shppongcart/src/ShopApp.js
> +      products: JSON.parse(localStorage.getItem('products')),
no need to use local storage in this case. redux is enough for this assignment

2019-10-16 05:51 UTC, swapnil-webonise requested changes

2019-10-16 05:51 UTC, swapnil-webonise commented on shppongcart/src/CheckoutProducts.js
> +    }
Indentation?

2019-10-16 05:51 UTC, swapnil-webonise commented on shppongcart/src/CheckoutProducts.js
> +    if (this.countProducts() === 0) {
we can write like

`if (!this.countProducts()) {`

2019-10-16 05:51 UTC, swapnil-webonise commented on shppongcart/src/ShopApp.js
> +    for (let i = 0; i < this.props.products.length; i++) {
use `map` instead of for loop

2019-10-16 09:07 UTC, swapnil-webonise approved these changes

2019-10-16 09:08 UTC, swapnil-webonise commented
@deepakb-webonise Merge the PR if fine from your side

2019-10-16 09:24 UTC, deepakb-webonise approved these changes

2019-10-16 09:24 UTC, deepakb-webonise commented on shppongcart/src/CheckoutProducts.js
> +class CheckoutProducts extends React.Component {
a functional component can be used here

2019-10-16 09:25 UTC, deepakb-webonise approved these changes

2019-10-16 09:25 UTC, deepakb-webonise commented on shppongcart/src/store/reducer/actionReducer.js
> +    case 'ADD_PRODUCT':
use constant instead of a string.

2019-10-16 12:22 UTC, merged